#!/bin/bash

product=$1
version=$2

communitypath='/conf/'
entpath='/resources/cassandra/conf/'
source ~/.getdatastax.cfg

user=$username
pass=$pwd
dsxdir=$datastax_dir

logback=false

function linux_edits() 
{
	echo "Editing cassandra.yaml and logging file to write to ${dsxdir}"
    	sed -i  "s:/var/lib/cassandra:${dsxdir}${ctype}/${version}:g" ${dsxdir}${ctype}/${version}${confpath}/cassandra.yaml 
    	if [ $logback == true ]; then
    		sed -i  "s:\${cassandra.logdir}:${dsxdir}${ctype}/${version}:g" ${dsxdir}${ctype}/${version}${confpath}logback.xml 
    	else
		sed -i  "s:/var/log/cassandra:${dsxdir}${ctype}/${version}:g" ${dsxdir}${ctype}/${version}${confpath}/log4j-server.properties
    	fi
}

function mac_edits() 
{
	echo "Editing cassandra.yaml and logging file to write to ${dsxdir}"
	sed -i  _bk "s:/var/lib/cassandra:${dsxdir}$ctype/${version}:g" ${dsxdir}${ctype}/${version}${confpath}/cassandra.yaml 
	if [ $logback == true ]; then
		sed -i  _bk "s:\${cassandra.logdir}:${dsxdir}$ctype/${version}:g" ${dsxdir}${ctype}/${version}${confpath}logback.xml
	else
		sed -i  _bk "s:/var/log/cassandra:${dsxdir}$ctype/${version}:g" ${dsxdir}${ctype}/${version}${confpath}/log4j-server.properties
	fi
}
function community_check()
{
	thisversion=${version:0:1}${version:2:1}
	if [ "${thisversion}" -ge 21 ]; then
		logback=true
	fi
 }

 function enterprise_check()
 {
 	thisversion=${version:0:1}${version:2:1}
 	if [ ""${thisversion}"" -ge 47 ]; then
		logback=true
	fi
 }


echo ${version:0:1}

if [ $product = dsc ]; then
 	echo "Downloading DataStax Community ${version}"
 	confpath=$communitypath
 	ctype=community
	curl -L http://downloads.datastax.com/community/dsc-cassandra-${version}-bin.tar.gz | tar xz

	if [ ! -d "${dsxdir}community" ]; then
		mkdir -p ${dsxdir}community
	fi

	mv dsc-cassandra-${version} ${dsxdir}community/${version}
	community_check
	#Need slightly different args for sed since Linux and Mac(BSD) operate with diff args
	if [ "$(uname)" == "Linux" ]; then
		linux_edits				 
	elif [ "$(uname)" == "Darwin" ]; then
		mac_edits   
	fi

#DataStax Enterprise Download
elif [ $product = dse ]; then
 	echo "Downloading DSE ${version}"
 	confpath=$entpath
 	ctype=enterprise
	curl -u $user:$pass -L http://downloads.datastax.com/enterprise/dse-${version}-bin.tar.gz | tar xz ; 

	if [ ! -d "${dsxdir}enterprise" ]; then
       mkdir -p ${dsxdir}enterprise
	fi

	mv dse-${version} ${dsxdir}enterprise/${version}
	enterprise_check
	#Need slightly different args for sed since Linux and Mac(BSD) operate with diff args
	if [ "$(uname)" == "Linux" ]; then
                linux_edits  
	elif [ "$(uname)" == "Darwin" ]; then
		mac_edits		  
	fi

#DataStax OpsCenter Download
elif [ $product = ops ]; then
 	echo "Downloading OpsCenter ${version}"
	curl -L http://downloads.datastax.com/community/opscenter-${version}.tar.gz | tar xz; 

	if [ ! -d "${dsxdir}opscenter" ]; then
        mkdir -p ${dsxdir}opscenter
	fi

	mv opscenter-${version} ${dsxdir}opscenter/${version}
else
	echo "Invalid Product"
fi


echo "Done."
